# Generated by Django 3.2.12 on 2022-02-28 01:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveIntegerField(verbose_name='注文したときの商品の価格')),
                ('product_name', models.PositiveIntegerField(verbose_name='注文時の商品の名前')),
                ('pattern_img', models.ImageField(upload_to='shop/pattern/', verbose_name='画像')),
                ('pattern_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='注文時の糸の太さ')),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='商品の個数')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{6})$')], verbose_name='色')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='本数')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderpatternrecipe',
            name='target',
        ),
        migrations.RemoveField(
            model_name='orderpatternrecipe',
            name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='prefectures',
            new_name='prefecture',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
        migrations.AddField(
            model_name='order',
            name='deliverd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配送処理日時'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支払い確認日時'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='注文した人'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='OrderPatternRecipe',
        ),
        migrations.AddField(
            model_name='orderdetailpattern',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='注文(1種類に対しての注文)'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='注文'),
        ),
    ]
